/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAddMoneyRouteImport } from './routes/_authenticated/add-money'
import { Route as AuthenticatedEarnRouteImport } from './routes/_authenticated/earn'
import { Route as AuthenticatedHostRouteImport } from './routes/_authenticated/host'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedMoreRouteImport } from './routes/_authenticated/more'
import { Route as AuthenticatedMyGamesRouteImport } from './routes/_authenticated/my-games'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedWithdrawRouteImport } from './routes/_authenticated/withdraw'
import { Route as GamesCategoryRouteImport } from './routes/games.$category'
import { Route as TournamentsIndexRouteImport } from './routes/tournaments.index'
import { Route as TournamentsIdRouteImport } from './routes/tournaments.$id'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin.payments'
import { Route as AuthenticatedAdminTournamentsRouteImport } from './routes/_authenticated/admin.tournaments'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedWithdrawMethodRouteImport } from './routes/_authenticated/withdraw.$method'
import { Route as ApiPublicWebhooksZapupiRouteImport } from './routes/api/public/webhooks/zapupi'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAddMoneyRoute = AuthenticatedAddMoneyRouteImport.update({
  id: '/add-money',
  path: '/add-money',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEarnRoute = AuthenticatedEarnRouteImport.update({
  id: '/earn',
  path: '/earn',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHostRoute = AuthenticatedHostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMoreRoute = AuthenticatedMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyGamesRoute = AuthenticatedMyGamesRouteImport.update({
  id: '/my-games',
  path: '/my-games',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWithdrawRoute = AuthenticatedWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const GamesCategoryRoute = GamesCategoryRouteImport.update({
  id: '/games/$category',
  path: '/games/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIndexRoute = TournamentsIndexRouteImport.update({
  id: '/tournaments/',
  path: '/tournaments/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIdRoute = TournamentsIdRouteImport.update({
  id: '/tournaments/$id',
  path: '/tournaments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/admin/payments',
    path: '/admin/payments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTournamentsRoute =
  AuthenticatedAdminTournamentsRouteImport.update({
    id: '/admin/tournaments',
    path: '/admin/tournaments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWithdrawMethodRoute =
  AuthenticatedWithdrawMethodRouteImport.update({
    id: '/$method',
    path: '/$method',
    getParentRoute: () => AuthenticatedWithdrawRoute,
  } as any)
const ApiPublicWebhooksZapupiRoute = ApiPublicWebhooksZapupiRouteImport.update({
  id: '/api/public/webhooks/zapupi',
  path: '/api/public/webhooks/zapupi',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/add-money': typeof AuthenticatedAddMoneyRoute
  '/earn': typeof AuthenticatedEarnRoute
  '/host': typeof AuthenticatedHostRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/more': typeof AuthenticatedMoreRoute
  '/my-games': typeof AuthenticatedMyGamesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/withdraw': typeof AuthenticatedWithdrawRouteWithChildren
  '/games/$category': typeof GamesCategoryRoute
  '/tournaments/$id': typeof TournamentsIdRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/tournaments': typeof AuthenticatedAdminTournamentsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/withdraw/$method': typeof AuthenticatedWithdrawMethodRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/webhooks/zapupi': typeof ApiPublicWebhooksZapupiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/add-money': typeof AuthenticatedAddMoneyRoute
  '/earn': typeof AuthenticatedEarnRoute
  '/host': typeof AuthenticatedHostRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/more': typeof AuthenticatedMoreRoute
  '/my-games': typeof AuthenticatedMyGamesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/withdraw': typeof AuthenticatedWithdrawRouteWithChildren
  '/games/$category': typeof GamesCategoryRoute
  '/tournaments/$id': typeof TournamentsIdRoute
  '/tournaments': typeof TournamentsIndexRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/tournaments': typeof AuthenticatedAdminTournamentsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/withdraw/$method': typeof AuthenticatedWithdrawMethodRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/webhooks/zapupi': typeof ApiPublicWebhooksZapupiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/add-money': typeof AuthenticatedAddMoneyRoute
  '/_authenticated/earn': typeof AuthenticatedEarnRoute
  '/_authenticated/host': typeof AuthenticatedHostRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/more': typeof AuthenticatedMoreRoute
  '/_authenticated/my-games': typeof AuthenticatedMyGamesRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/_authenticated/withdraw': typeof AuthenticatedWithdrawRouteWithChildren
  '/games/$category': typeof GamesCategoryRoute
  '/tournaments/$id': typeof TournamentsIdRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/tournaments': typeof AuthenticatedAdminTournamentsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/withdraw/$method': typeof AuthenticatedWithdrawMethodRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/webhooks/zapupi': typeof ApiPublicWebhooksZapupiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/add-money'
    | '/earn'
    | '/host'
    | '/leaderboard'
    | '/more'
    | '/my-games'
    | '/notifications'
    | '/profile'
    | '/wallet'
    | '/withdraw'
    | '/games/$category'
    | '/tournaments/$id'
    | '/tournaments/'
    | '/admin/payments'
    | '/admin/tournaments'
    | '/admin/users'
    | '/withdraw/$method'
    | '/admin/'
    | '/api/public/webhooks/zapupi'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/add-money'
    | '/earn'
    | '/host'
    | '/leaderboard'
    | '/more'
    | '/my-games'
    | '/notifications'
    | '/profile'
    | '/wallet'
    | '/withdraw'
    | '/games/$category'
    | '/tournaments/$id'
    | '/tournaments'
    | '/admin/payments'
    | '/admin/tournaments'
    | '/admin/users'
    | '/withdraw/$method'
    | '/admin'
    | '/api/public/webhooks/zapupi'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/add-money'
    | '/_authenticated/earn'
    | '/_authenticated/host'
    | '/_authenticated/leaderboard'
    | '/_authenticated/more'
    | '/_authenticated/my-games'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/wallet'
    | '/_authenticated/withdraw'
    | '/games/$category'
    | '/tournaments/$id'
    | '/tournaments/'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/tournaments'
    | '/_authenticated/admin/users'
    | '/_authenticated/withdraw/$method'
    | '/_authenticated/admin/'
    | '/api/public/webhooks/zapupi'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  GamesCategoryRoute: typeof GamesCategoryRoute
  TournamentsIdRoute: typeof TournamentsIdRoute
  TournamentsIndexRoute: typeof TournamentsIndexRoute
  ApiPublicWebhooksZapupiRoute: typeof ApiPublicWebhooksZapupiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/add-money': {
      id: '/_authenticated/add-money'
      path: '/add-money'
      fullPath: '/add-money'
      preLoaderRoute: typeof AuthenticatedAddMoneyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/earn': {
      id: '/_authenticated/earn'
      path: '/earn'
      fullPath: '/earn'
      preLoaderRoute: typeof AuthenticatedEarnRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/host': {
      id: '/_authenticated/host'
      path: '/host'
      fullPath: '/host'
      preLoaderRoute: typeof AuthenticatedHostRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/more': {
      id: '/_authenticated/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof AuthenticatedMoreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-games': {
      id: '/_authenticated/my-games'
      path: '/my-games'
      fullPath: '/my-games'
      preLoaderRoute: typeof AuthenticatedMyGamesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/withdraw': {
      id: '/_authenticated/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof AuthenticatedWithdrawRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/games/$category': {
      id: '/games/$category'
      path: '/games/$category'
      fullPath: '/games/$category'
      preLoaderRoute: typeof GamesCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/': {
      id: '/tournaments/'
      path: '/tournaments'
      fullPath: '/tournaments/'
      preLoaderRoute: typeof TournamentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$id': {
      id: '/tournaments/$id'
      path: '/tournaments/$id'
      fullPath: '/tournaments/$id'
      preLoaderRoute: typeof TournamentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/tournaments': {
      id: '/_authenticated/admin/tournaments'
      path: '/admin/tournaments'
      fullPath: '/admin/tournaments'
      preLoaderRoute: typeof AuthenticatedAdminTournamentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/withdraw/$method': {
      id: '/_authenticated/withdraw/$method'
      path: '/$method'
      fullPath: '/withdraw/$method'
      preLoaderRoute: typeof AuthenticatedWithdrawMethodRouteImport
      parentRoute: typeof AuthenticatedWithdrawRoute
    }
    '/api/public/webhooks/zapupi': {
      id: '/api/public/webhooks/zapupi'
      path: '/api/public/webhooks/zapupi'
      fullPath: '/api/public/webhooks/zapupi'
      preLoaderRoute: typeof ApiPublicWebhooksZapupiRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedWithdrawRouteChildren {
  AuthenticatedWithdrawMethodRoute: typeof AuthenticatedWithdrawMethodRoute
}

const AuthenticatedWithdrawRouteChildren: AuthenticatedWithdrawRouteChildren = {
  AuthenticatedWithdrawMethodRoute: AuthenticatedWithdrawMethodRoute,
}

const AuthenticatedWithdrawRouteWithChildren =
  AuthenticatedWithdrawRoute._addFileChildren(
    AuthenticatedWithdrawRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAddMoneyRoute: typeof AuthenticatedAddMoneyRoute
  AuthenticatedEarnRoute: typeof AuthenticatedEarnRoute
  AuthenticatedHostRoute: typeof AuthenticatedHostRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedMoreRoute: typeof AuthenticatedMoreRoute
  AuthenticatedMyGamesRoute: typeof AuthenticatedMyGamesRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedWithdrawRoute: typeof AuthenticatedWithdrawRouteWithChildren
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminTournamentsRoute: typeof AuthenticatedAdminTournamentsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAddMoneyRoute: AuthenticatedAddMoneyRoute,
  AuthenticatedEarnRoute: AuthenticatedEarnRoute,
  AuthenticatedHostRoute: AuthenticatedHostRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedMoreRoute: AuthenticatedMoreRoute,
  AuthenticatedMyGamesRoute: AuthenticatedMyGamesRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedWithdrawRoute: AuthenticatedWithdrawRouteWithChildren,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminTournamentsRoute: AuthenticatedAdminTournamentsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  GamesCategoryRoute: GamesCategoryRoute,
  TournamentsIdRoute: TournamentsIdRoute,
  TournamentsIndexRoute: TournamentsIndexRoute,
  ApiPublicWebhooksZapupiRoute: ApiPublicWebhooksZapupiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
