revoke all on function public.has_role(uuid, public.app_role) from public, anon;
revoke all on function public.handle_new_user() from public, anon, authenticated;
revoke all on function public.wallet_apply(uuid,text,numeric,uuid,text) from public, anon, authenticated;
revoke all on function public.join_tournament(uuid) from public, anon;
revoke all on function public.request_withdrawal(numeric, text) from public, anon;
revoke all on function public.admin_settle_withdrawal(uuid, text, text) from public, anon;
revoke all on function public.admin_publish_room(uuid, text, text) from public, anon;
revoke all on function public.get_room_details(uuid) from public, anon;
revoke all on function public.admin_publish_results(uuid) from public, anon;
revoke all on function public.admin_settle_deposit(uuid, text) from public, anon;
revoke all on function public.create_deposit(numeric, text) from public, anon;
grant execute on function public.has_role(uuid, public.app_role) to authenticated;
grant execute on function public.join_tournament(uuid) to authenticated;
grant execute on function public.request_withdrawal(numeric, text) to authenticated;
grant execute on function public.admin_settle_withdrawal(uuid, text, text) to authenticated;
grant execute on function public.admin_publish_room(uuid, text, text) to authenticated;
grant execute on function public.get_room_details(uuid) to authenticated;
grant execute on function public.admin_publish_results(uuid) to authenticated;
grant execute on function public.admin_settle_deposit(uuid, text) to authenticated;
grant execute on function public.create_deposit(numeric, text) to authenticated;